steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/testblazorapp-417308/webapiforgooglecloud', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/testblazorapp-417308/webapiforgooglecloud']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'webapiforgooglecloud', '--image', 'gcr.io/testblazorapp-417308/webapiforgooglecloud', '--region', 'europe-west4', '--allow-unauthenticated']
images:
- gcr.io/testblazorapp-417308/webapiforgooglecloud